# vim:ft=kitty

## name: Synthwave '84
## license: MIT

background #2a0a22
foreground #e2e2ff
selection_background #4d21fc
selection_foreground #e2e2ff
url_color #03edf9
cursor #ff6ac1
cursor_text_color #1a1a2e

# Tabs
active_tab_background #ff6ac1
active_tab_foreground #1a1a2e
inactive_tab_background #2d2b55
inactive_tab_foreground #a09fc0

# Windows
active_border_color #03edf9
inactive_border_color #4d3a7a

# normal
color0 #2d2b55
color1 #ff6ac1
color2 #72f1b8
color3 #fede5d
color4 #4d21fc
color5 #e1acff
color6 #03edf9
color7 #e2e2ff

# bright
color8  #3d3b6e
color9  #ff92d0
color10 #a8ffde
color11 #ffef99
color12 #7b5fff
color13 #f5d6ff
color14 #87f5ff
color15 #ffffff
